AES_KEY = "QwErPOiuAsDfLKjh"
AES_IV = "QAzPLmrfVuhBxxnn"
OPENAI_API_KEY="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"